# Simple makefile for CLEANING ONLY
#
# https://stackoverflow.com/questions/2481269/how-to-make-a-simple-c-makefile
#
# Compiles, runs, and cleans NameSpaces.cpp
# Use TABS
#
# -f so this will succeed even if the files don't exist


clean:
	rm -f *.exe
